### ISSUE TITLE
clara-tools not working with 0.8.9

### ISSUE THREAD

**Issue by devn** [rbrush/clara-tools#2]
Hi Ryan,

I know this repo is considered experimental, but I think it'd be a shame to let it succumb to bit rot.

It looks like `show-logic-graph` works, but `show-session` does not:

``` clojure
IllegalArgumentException No implementation of method: :components of protocol: #'clara.rules.engine/ISession found for class: clojure.lang.PersistentVector  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
```

What would it take to get this working again with 0.8.9? I've spent a little bit of time looking through source, trying to figure out what broke, but I must admit I'm having some trouble given the delta in versions.

**Comment by devn** [comment]
Actually, I was incorrect. `show-session` works. I accidentally was passing it a `nil` session.

@rbrush Any chance you'd be willing to release `clara-tools`?

**Comment by rbrush** [comment]
It's still a bug that we didn't report something more helpful than that exception, so we can use this issue to track that.

I'm okay with pushing out a release. I'd like to see this project pick up some momentum. Efforts have been focused on clara-rules itself (and our use of it), but that can change if there is interested.

If you're interested in doing some work to move it forward, I'd be happy to pull in changes.

**Comment by devn** [comment]
@rbrush RE: project momentum: I am surprised as well. I think there are some great opportunities here to improve upon explanations, help people reason about large sets of rules, diff rules, maybe even authoring.

In any event, I'll go ahead and make that exception a bit more helpful.

Thanks!
