### ISSUE TITLE
When using accumulators, show-session not working

### ISSUE THREAD

**Issue by devn** [rbrush/clara-tools#5]
Any pointers? I'm down to fix this, but am not quite sure where to begin.

Also, FWIW -- I created a #clara slack channel at http://clojurians.net/. Would be great to have you in there, if that's the sort of thing you're interested in.

Cheers,
Devin

**Comment by rbrush** [comment]
So I made an ugly fix for this at the branch below, along with upgrading several dependencies. Accumulators don't necessarily keep a full history of their inputs (e.g., if they sum a bunch of numbers, they only keep a sum), so we won't trace everything back to its original inputs. But displaying accumulators should produce _something_, which the branch below does.

The change is pretty ugly...basically the accumulated value is a treated as a type of fact, and logic has been added to deal with it and the accumulator structure on display. It's probably okay to demonstrate an idea, along with the rest of this project.

https://github.com/rbrush/clara-tools/tree/accum_updates

**Comment by devn** [comment]
This saved us a couple hours today, and is greatly appreciated. We were just about at the point where we understood why it wasn't showing up, and then you swooped in with the fix.

Thanks a ton, Ryan!

**Comment by rbrush** [comment]
Glad it helps!

I think we still need to take a harder look at how we deal with accumulators...the fix is more of a workaround to get _something_ to display for accumulators and not really a well-considered strategy. Any contributions in this space are welcome...as you may have guessed my time is primarily spent on the core clara-rules project (which I use heavily in production), so this one is more of a hobby. ;)

**Comment by devn** [comment]
Yeah, understood on all fronts.

I suspect we'll spend some more time as a team working on clara-tools over the next 3-6 months. Right now we're mainly using it as a way to demo what we're working on, but I suspect that we'll extend it to do some fancier graphs at some point and add some UI sparkle. We've talked about a few little things like adding a scrollbar to the session fact list, letting you filter the list, auto-centering the graph, etc. Also providing an alternative way of configuring what is shown for different fact types.

Anyway, thanks again for your help! We're going to be using Clara at healthfinch, and so far, so good!

Cheers,
Devin
